"""
Snapshot I/O utilities for molecular simulations.
"""

"""
    write_xyz(path, pos; types=nothing, comment="")

Write positions to XYZ file format.

Inputs:
- `path`: File path to write
- `pos`: Matrix{Float64} of size (3, N) where N is number of particles, columns are particles
- `types`: Optional Vector{Int} of particle types (default: all type 1, or use "Ar" as default)
- `comment`: Optional comment string for second line

XYZ format:
- Line 1: N (number of particles)
- Line 2: comment
- Lines 3 to N+2: "Ar x y z" for each particle (or type name if types provided)

If types is provided, uses type names "Ar1", "Ar2", etc. based on type ID.
Otherwise, uses "Ar" for all particles.
"""
function write_xyz(path::String, pos::Matrix{Float64}; types::Union{Vector{Int}, Nothing}=nothing, comment::String="")
    N = size(pos, 2)
    if size(pos, 1) != 3
        error("pos must be (3, N) matrix, got size $(size(pos))")
    end
    
    open(path, "w") do io
        # Line 1: number of particles
        println(io, N)
        
        # Line 2: comment
        if comment == ""
            println(io, "Generated by MolSim")
        else
            println(io, comment)
        end
        
        # Lines 3 to N+2: particle coordinates
        if types === nothing
            # All particles are type "Ar"
            @inbounds for i in 1:N
                println(io, "Ar $(pos[1, i]) $(pos[2, i]) $(pos[3, i])")
            end
        else
            if length(types) != N
                error("types length $(length(types)) must match N=$N")
            end
            @inbounds for i in 1:N
                type_id = types[i]
                type_name = "Ar$(type_id)"
                println(io, "$type_name $(pos[1, i]) $(pos[2, i]) $(pos[3, i])")
            end
        end
    end
    
    return nothing
end
